/**
 * This file holds a JSON object that contains potential dropdown options
 */

export const dropDownOptions = [
  {'id': 0,
  'title': 'Administrative Tribunals Support Service of Canada',
  'selected': false,
  'key': 'department'},
  {'id': 1,
  'title': 'Agriculture and Agri-Food Canada',
  'selected': false,
  'key': 'department'},
  {'id': 2,
  'title': 'Atlantic Canada Opportunities Agency',
  'selected': false,
  'key': 'department'},
  {'id': 3,
  'title': 'Auditor General of Canada, Office of the',
  'selected': false,
  'key': 'department'},
  {'id': 4,
  'title': 'Canada Border Services Agency',
  'selected': false,
  'key': 'department'},
  {'id': 5,
  'title': 'Canada Council for the Arts',
  'selected': false,
  'key': 'department'},
  {'id': 6,
  'title': 'Canada Economic Development for Quebec Regions',
  'selected': false,
  'key': 'department'},
  {'id': 7,
  'title': 'Canada Energy Regulator',
  'selected': false,
  'key': 'department'},
  {'id': 8,
  'title': 'Canada Industrial Relations Board',
  'selected': false,
  'key': 'department'},
  {'id': 9,
  'title': 'Canada Mortgage and Housing Corporation',
  'selected': false,
  'key': 'department'},
  {'id': 10,
  'title': 'Canada Revenue Agency',
  'selected': false,
  'key': 'department'},
  {'id': 11,
  'title': 'Canada School of Public Service',
  'selected': false,
  'key': 'department'},
  {'id': 12,
  'title': 'Canadian Air Transport Security Authority',
  'selected': false,
  'key': 'department'},
  {'id': 13,
  'title': 'Canadian Commercial Corporation',
  'selected': false,
  'key': 'department'},
  {'id': 14,
  'title': 'Canadian Dairy Commission',
  'selected': false,
  'key': 'department'},
  {'id': 15,
  'title': 'Canadian Food Inspection Agency',
  'selected': false,
  'key': 'department'},
  {'id': 16,
  'title': 'Canadian Grain Commission',
  'selected': false,
  'key': 'department'},
  {'id': 17,
  'title': 'Canadian Heritage',
  'selected': false,
  'key': 'department'},
  {'id': 18,
  'title': 'Canadian Human Rights Commission',
  'selected': false,
  'key': 'department'},
  {'id': 19,
  'title': 'Canadian Institutes of Health Research',
  'selected': false,
  'key': 'department'},
  {'id': 20,
  'title': 'Canadian Intergovernmental Conference Secretariat',
  'selected': false,
  'key': 'department'},
  {'id': 21,
  'title': 'Canadian Museum for Human Rights',
  'selected': false,
  'key': 'department'},
  {'id': 22,
  'title': 'Canadian Museum of History',
  'selected': false,
  'key': 'department'},
  {'id': 23,
  'title': 'Canadian Museum of Nature',
  'selected': false,
  'key': 'department'},
  {'id': 24,
  'title': 'Canadian Northern Economic Development Agency',
  'selected': false,
  'key': 'department'},
  {'id': 25,
  'title': 'Canadian Nuclear Safety Commission',
  'selected': false,
  'key': 'department'},
  {'id': 26,
  'title': 'Canadian Radio-television and Telecommunications Commission',
  'selected': false,
  'key': 'department'},
  {'id': 27,
  'title': 'Canadian Space Agency',
  'selected': false,
  'key': 'department'},
  {'id': 28,
  'title': 'Canadian Tourism Commission',
  'selected': false,
  'key': 'department'},
  {'id': 29,
  'title': 'Canadian Transportation Agency',
  'selected': false,
  'key': 'department'},
  {'id': 30,
  'title': 'Civilian Review and Complaints Commission for the RCMP',
  'selected': false,
  'key': 'department'},
  {'id': 31,
  'title': 'Copyright Board Canada',
  'selected': false,
  'key': 'department'},
  {'id': 32,
  'title': 'Correctional Service Canada',
  'selected': false,
  'key': 'department'},
  {'id': 33,
  'title': 'Courts Administration Service',
  'selected': false,
  'key': 'department'},
  {'id': 34,
  'title': 'Defence Construction Canada',
  'selected': false,
  'key': 'department'},
  {'id': 35,
  'title': 'Defence Research and Development Canada (DRDC)',
  'selected': false,
  'key': 'department'},
  {'id': 36,
  'title': 'Employment and Social Development Canada',
  'selected': false,
  'key': 'department'},
  {'id': 37,
  'title': 'Environment and Climate Change Canada',
  'selected': false,
  'key': 'department'},
  {'id': 38,
  'title': 'Farm Products Council of Canada',
  'selected': false,
  'key': 'department'},
  {'id': 39, 'title': 'Federal Court', 'selected': false, 'key': 'department'},
  {'id': 40,
  'title': 'Federal Court of Appeal',
  'selected': false,
  'key': 'department'},
  {'id': 41,
  'title': 'Federal Economic Development Agency for Southern Ontario',
  'selected': false,
  'key': 'department'},
  {'id': 42,
  'title': 'Federal Public Sector Labour Relations and Employment Board',
  'selected': false,
  'key': 'department'},
  {'id': 43, 'title': 'Finance Canada', 'selected': false, 'key': 'department'},
  {'id': 44,
  'title': 'Financial Consumer Agency of Canada',
  'selected': false,
  'key': 'department'},
  {'id': 45,
  'title': 'Fisheries and Oceans Canada',
  'selected': false,
  'key': 'department'},
  {'id': 46,
  'title': 'Global Affairs Canada',
  'selected': false,
  'key': 'department'},
  {'id': 47, 'title': 'Health Canada', 'selected': false, 'key': 'department'},
  {'id': 48,
  'title': 'House of Commons',
  'selected': false,
  'key': 'department'},
  {'id': 49,
  'title': 'Immigration and Refugee Board of Canada',
  'selected': false,
  'key': 'department'},
  {'id': 50,
  'title': 'Immigration, Refugees and Citizenship Canada',
  'selected': false,
  'key': 'department'},
  {'id': 51,
  'title': 'Impact Assessment Agency of Canada',
  'selected': false,
  'key': 'department'},
  {'id': 52,
  'title': 'Indigenous and Northern Affairs Canada',
  'selected': false,
  'key': 'department'},
  {'id': 53,
  'title': 'Indigenous Services Canada',
  'selected': false,
  'key': 'department'},
  {'id': 54,
  'title': 'Infrastructure Canada',
  'selected': false,
  'key': 'department'},
  {'id': 55, 'title': 'Ingenium', 'selected': false, 'key': 'department'},
  {'id': 56,
  'title': 'Innovation, Science and Economic Development Canada',
  'selected': false,
  'key': 'department'},
  {'id': 57,
  'title': 'International Development Research Centre',
  'selected': false,
  'key': 'department'},
  {'id': 58,
  'title': 'International Joint Commission',
  'selected': false,
  'key': 'department'},
  {'id': 59, 'title': 'Justice Canada', 'selected': false, 'key': 'department'},
  {'id': 60,
  'title': 'Laurentian Pilotage Authority Canada',
  'selected': false,
  'key': 'department'},
  {'id': 61,
  'title': 'Library and Archives Canada',
  'selected': false,
  'key': 'department'},
  {'id': 62,
  'title': 'Library of Parliament',
  'selected': false,
  'key': 'department'},
  {'id': 63,
  'title': 'Military Grievances External Review Committee',
  'selected': false,
  'key': 'department'},
  {'id': 64,
  'title': 'Military Police Complaints Commission of Canada',
  'selected': false,
  'key': 'department'},
  {'id': 65,
  'title': 'National Arts Centre',
  'selected': false,
  'key': 'department'},
  {'id': 66,
  'title': 'National Capital Commission',
  'selected': false,
  'key': 'department'},
  {'id': 67,
  'title': 'National Defence',
  'selected': false,
  'key': 'department'},
  {'id': 68,
  'title': 'National Film Board of Canada',
  'selected': false,
  'key': 'department'},
  {'id': 69,
  'title': 'National Research Council Canada',
  'selected': false,
  'key': 'department'},
  {'id': 70,
  'title': 'Natural Resources Canada',
  'selected': false,
  'key': 'department'},
  {'id': 71,
  'title': 'Natural Sciences and Engineering Research Council of Canada',
  'selected': false,
  'key': 'department'},
  {'id': 72,
  'title': 'Northern Pipeline Agency',
  'selected': false,
  'key': 'department'},
  {'id': 73,
  'title': 'Office of the Chief Electoral Officer',
  'selected': false,
  'key': 'department'},
  {'id': 74,
  'title': 'Office of the Commissioner for Federal Judicial Affairs Canada',
  'selected': false,
  'key': 'department'},
  {'id': 75,
  'title': 'Office of the Commissioner of Official Languages',
  'selected': false,
  'key': 'department'},
  {'id': 76,
  'title': 'Office of the Conflict of Interest and Ethics Commissioner',
  'selected': false,
  'key': 'department'},
  {'id': 77,
  'title': 'Office of the Information Commissioner of Canada',
  'selected': false,
  'key': 'department'},
  {'id': 78,
  'title': 'Office of the Privacy Commissioner of Canada',
  'selected': false,
  'key': 'department'},
  {'id': 79,
  'title': 'Office of the Secretary to the Governor General',
  'selected': false,
  'key': 'department'},
  {'id': 80,
  'title': 'Office of the Superintendent of Financial Institutions Canada',
  'selected': false,
  'key': 'department'},
  {'id': 81,
  'title': 'Pacific Pilotage Authority Canada',
  'selected': false,
  'key': 'department'},
  {'id': 82, 'title': 'Parks Canada', 'selected': false, 'key': 'department'},
  {'id': 83,
  'title': 'Parliamentary Budget Officer',
  'selected': false,
  'key': 'department'},
  {'id': 84,
  'title': 'Parole Board of Canada',
  'selected': false,
  'key': 'department'},
  {'id': 85,
  'title': 'Patented Medicine Prices Review Board',
  'selected': false,
  'key': 'department'},
  {'id': 86,
  'title': 'Polar Knowledge Canada',
  'selected': false,
  'key': 'department'},
  {'id': 87, 'title': 'PPP Canada', 'selected': false, 'key': 'department'},
  {'id': 88,
  'title': "Prime Minister's Office",
  'selected': false,
  'key': 'department'},
  {'id': 89,
  'title': 'Privy Council Office',
  'selected': false,
  'key': 'department'},
  {'id': 90,
  'title': 'Public Health Agency of Canada',
  'selected': false,
  'key': 'department'},
  {'id': 91,
  'title': 'Public Prosecution Service of Canada',
  'selected': false,
  'key': 'department'},
  {'id': 92,
  'title': 'Public Safety Canada',
  'selected': false,
  'key': 'department'},
  {'id': 93,
  'title': 'Public Service Commission',
  'selected': false,
  'key': 'department'},
  {'id': 94,
  'title': 'Public Services and Procurement Canada',
  'selected': false,
  'key': 'department'},
  {'id': 95,
  'title': 'Royal Canadian Mint',
  'selected': false,
  'key': 'department'},
  {'id': 96,
  'title': 'Royal Canadian Mounted Police',
  'selected': false,
  'key': 'department'},
  {'id': 97,
  'title': 'Senate of Canada',
  'selected': false,
  'key': 'department'},
  {'id': 98,
  'title': 'Shared Services Canada',
  'selected': false,
  'key': 'department'},
  {'id': 99,
  'title': 'Social Sciences and Humanities Research Council of Canada',
  'selected': false,
  'key': 'department'},
  {'id': 100,
  'title': 'Standards Council of Canada',
  'selected': false,
  'key': 'department'},
  {'id': 101,
  'title': 'Statistics Canada',
  'selected': false,
  'key': 'department'},
  {'id': 102,
  'title': 'Supreme Court of Canada',
  'selected': false,
  'key': 'department'},
  {'id': 103,
  'title': 'Tax Court of Canada',
  'selected': false,
  'key': 'department'},
  {'id': 104,
  'title': 'The Federal Bridge Corporation Limited',
  'selected': false,
  'key': 'department'},
  {'id': 105,
  'title': 'Transportation Appeal Tribunal of Canada',
  'selected': false,
  'key': 'department'},
  {'id': 106,
  'title': 'Transportation Safety Board of Canada',
  'selected': false,
  'key': 'department'},
  {'id': 107,
  'title': 'Transport Canada',
  'selected': false,
  'key': 'department'},
  {'id': 108,
  'title': 'Treasury Board of Canada Secretariat',
  'selected': false,
  'key': 'department'},
  {'id': 109,
  'title': 'Veterans Affairs Canada',
  'selected': false,
  'key': 'department'},
  {'id': 110,
  'title': 'Veterans Review and Appeal Board',
  'selected': false,
  'key': 'department'},
  {'id': 111,
  'title': 'Western Economic Diversification Canada',
  'selected': false,
  'key': 'department'},
  {'id': 112,
  'title': 'Women and Gender Equality Canada',
  'selected': false,
  'key': 'department'}
]